apiVersion: 1

deleteDatasources:
  - name: Gluevenir Prometheus
    orgId: 1
  - name: Gluevenir Jaeger
    orgId: 1

datasources:
  - name: Gluevenir Prometheus
    uid: gluevenir-prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.2.1
      timeInterval: 5s
  - name: Gluevenir Jaeger
    uid: gluevenir-jaeger
    orgId: 1
    type: jaeger
    access: proxy
    url: http://127.0.0.1:16686/traces
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: gluevenir-prometheus
